### ISSUE TITLE
SLURM

### ISSUE THREAD

**Issue by harryherold** [cc-hpc-itwm/GPI-2#16]
Is there a work around for the gaspi_run script with slurm ??
The ssh connections in the script are very bad for slurm and i need a solution to use e.g srun.

**Comment by csimmend** [comment]
Easy solution: use mpi/gaspi interoperability.
(see readme in gpi2 install)

--
Dr. Christian Simmendinger
Pfaffenwaldring 38-40, 70569 Stuttgart
email: christian.simmendinger@t-systems.com
mobile phone: ++49-160-90526017

T-Systems Solutions for Research GmbH
Management Board: Bernd Flack (Chairman)
Commercial Register: Amtsgericht Muenchen, HRB 12 55 01, Registered Office: Wessling
VAT ident. no.: DE 193456493
________________________________
Von: Christian Herold [notifications@github.com]
Gesendet: Freitag, 6. Februar 2015 14:50
An: cc-hpc-itwm/GPI-2
Betreff: [GPI-2] SLURM (#16)


Is there a work around for the gaspi_run script with slurm ??
The ssh connections in the script are very bad for slurm and i need a solution to use e.g srun.

**Comment by harryherold** [comment]
I implemented a own script
