### ISSUE TITLE
what is the limit of GASPI_MAX_MSEGS

### ISSUE THREAD

**Issue by zorksylar** [cc-hpc-itwm/GPI-2#18]
The max number of segments can be created is `#define GASPI_MAX_MSEGS   (32)` in file `include/GASPI.h` 
I want to create thousands of segments, can i just modify  `#define GASPI_MAX_MSEGS   (1024)` 
and what is the limit of `GASPI_MAX_MSEGS` can be defined ? 

Thank you very much

**Comment by rumach** [comment]
@zorksylar in principle there's no real impediment for not having a larger GASPI_MAX_MSEGS and thus allow a higher number of segments. But there's a practical reason for such a "low" constant: the creation of a segment is an expensive operation. The idea is that one uses a few, possibly large, segments that are managed by the application.
We can continue the discussion of your use-case per email.

**Comment by zorksylar** [comment]
That helped a lot, thank you.
