### ISSUE TITLE
gaspi_write and gaspi_notify

### ISSUE THREAD

**Issue by harryherold** [cc-hpc-itwm/GPI-2#20]
Hi,
following situation:
I have many gaspi_write's (they address the same target rank) in the same queue(e.g. queue=1) and the rank executes a gaspi_wait-Operation on this queue(queue=1) and after that the rank posts a notify to this (empty) queue(queue=1).
Can it happens that the notify is faster than the write's ?

**Comment by rumach** [comment]
Hi @harryherold. No, it shouldn't happen.

**Comment by harryherold** [comment]
Thanks
