### ISSUE TITLE
where are the Cray devices?

### ISSUE THREAD

**Issue by jeffhammond** [cc-hpc-itwm/GPI-2#28]
I see there is support for Cray networks in [GASPI – A Failure Tolerant PGAS API for Asynchronous Dataflow on Heterogeneous Architectures](http://www.teraflop-workbench.de/htm/events/18thWorkshop_talks/18thWSSP_Christian_Simmendinger_PGAS.pdf): "GASPI Implementation for Cray Gemini, Aries: Hermit".

However, line 132 of the latest [GASPI.h](https://github.com/cc-hpc-itwm/GPI-2/blob/next/include/GASPI.h#L132) indicates that these are not implemented, at least in the version here on Github.

Is the Cray implementation going to be released at some point?  If so, when?

**Comment by rumach** [comment]
Unfortunately there is not yet a definitive plan of whether the Cray implementation will be released here on github.
