### ISSUE TITLE
Adhere to standard configure, make, make install workflow

### ISSUE THREAD

**Issue by Flamefire** [cc-hpc-itwm/GPI-2#34]
The current custom `install.sh` does make it difficult to integrate the GPI2 installation into standard workflows.
Please provide proper configure and make scripts instead of encapsulating it into a not fully-configurable custom procedure.

Example: the build must be done on a different machine or from a different user than the install. E.g. `make && sudo make install`

**Comment by acastanedam** [comment]
Hi, the actual `next` branch (and upcoming release) adopts such scheme, namely using autotools. The actual steps to configure and compile GPI-2 can be found in the corresponding README.
