### ISSUE TITLE
Failed to modify QP on RHEL 7.5 with OpenFabrics stack

### ISSUE THREAD

**Issue by Flamefire** [cc-hpc-itwm/GPI-2#47]
Executing a simple GPI2 Hello-World program fails with 

> [Rank    0]: Error 22 (Invalid argument) at (.../GPI-2-1.3.0/src/devices/ib/GPI2_IB.c:813):Failed to modify QP (libibverbs)
> [Rank    0]: Error at (GPI2_SN.c:648):Failed to read from 0

**Comment by Flamefire** [comment]
Happens also on 'next' branch

**Comment by rumach** [comment]
Thanks for reporting this. Unfortunately I can't reproduce it. Can you tell me what kind of system are you using? And is this a 'simple hello world' (init, hello, term) or with some modifications?

**Comment by Flamefire** [comment]
Rhel 7.5 with open fabrics IB.
GCC 6.4
hello World from the web site

**Comment by Flamefire** [comment]
Backtrace:

```
#0  _pgaspi_dev_qp_set_ready (gctx=0x423980 <glb_gaspi_ctx>, qp=0x459cb8, target=0, target_qp=204) at /home/h3/s3248973/build/GPI-2/src/devices/ib/GPI2_IB.c:911
#1  0x00000000004096fb in pgaspi_dev_connect_context (gctx=0x423980 <glb_gaspi_ctx>, i=0) at /home/h3/s3248973/build/GPI-2/src/devices/ib/GPI2_IB.c:962
#2  0x000000000041897b in pgaspi_connect_endpoint_to (rank=0, timeout_ms=30000) at GPI2_CM.c:80
#3  0x000000000040f815 in gaspi_sn_backend (arg=0x0) at GPI2_SN.c:1557
#4  0x00002aaaaaeebdd5 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00002aaaab500b3d in clone () from /usr/lib64/libc.so.6
```

Easily reproducible on taurus hpdlf partition.
