### ISSUE TITLE
Limit to low for GASPI_MAX_MSEGS

### ISSUE THREAD

**Issue by dhinf** [cc-hpc-itwm/GPI-2#51]
Why is the limit for GASPI_MAX_MSEGS per default 32? 

I don't agree with the explanation given in issue #18. The user should decide on his own how many segments he wants to use and not a default value.

Gaspi(GPI2) only supports one-sided communication between segment ids, here you need more than this number of segments at some point. Especially when using an abstraction on top of GASPI(GPI2).

**Comment by dhinf** [comment]
I propose to set the default to the possible maximum of 255 (unsigned char).

**Comment by acastanedam** [comment]
Hi, the actual next branch (and upcoming release) allows to setup in a pre-configuration step the maximum number of segments of  a particular run. Still such number must be less or equal than  GASPI_MAX_MSEGS=255.
Thanks for your feedback.
