### ISSUE TITLE
gaspi_segment_bind doesn't count in gaspi_segment_list

### ISSUE THREAD

**Issue by krzikalla** [cc-hpc-itwm/GPI-2#53]
The following code fails:

  gaspi_segment_id_t data[1];
  gaspi_segment_bind(0, somePtr, someSize, 0);
  assert(gaspi_segment_list(1, data) == GASPI_SUCCESS);

The problem is, that gaspi_segment_bind doesn't set the "trans" member of the own rank to 1. 
gaspi_segment_list then returns GASPI_ERROR, since there is a mismatch between mseg_cnt and the segments, which have set their "trans" members.
A workaround is an additional gaspi_segment_register call on the own rank.  
However, the standard says, that a bound segment "...can be accessed locally...".
Thus I'd say, that this is actually a GPI2 bug, which can be fixed by setting the "trans" member in 
gaspi_segment_bind and presumably in gaspi_segment_alloc.

**Comment by krzikalla** [comment]
After further investigations I can confirm, that an additional gaspi_segment_register call will fix the problem. 

I consider this a bug in GPI2, since after a gaspi_segment_bind without a gaspi_segment_register on the own rank the lib is an inconsistent state.

**Comment by dhinf** [comment]
But gaspi_segment_register is a non-local function. And for my use case a bind that only acts locally (as mentioned in standard) is necessary. Adding a non-local element is way to costly.

**Comment by dhinf** [comment]
By the way, i don't think that no developer of GPI2 cares about the issues here.

**Comment by rumach** [comment]
@krzikalla Thank you for reporting this. I think you're reasoning is correct. I'll fix this.

**Comment by dhinf** [comment]
@rumach So, issues are read, but your quite selective answering them. Good to know.
