### ISSUE TITLE
Another gaspi segment handling error 

### ISSUE THREAD

**Issue by krzikalla** [cc-hpc-itwm/GPI-2#54]
https://github.com/cc-hpc-itwm/GPI-2/blob/dd47c69f722407f1a36d80253bf2bb75686393f6/src/GPI2_SEG.c#L477

Using plain r as rank index is wrong. Instead the physical rank of the group member with index r must be used. Bites you, if your group indices contains holes and you call gaspi_segment_list afterwards.

**Comment by acastanedam** [comment]
Thank you for pointing this issue. We have tried to reproduce it by creating a group which does not contain one or two ranks of the pool of available ranks, registering in such group a specific number of segments and then calling `gaspi_segment_list` to check the id's of the assigned segments. However, that test does not show any problem. Would it be possible to get a small test/snippet from you to see clearly what is happening?

**Comment by acastanedam** [comment]
Just to be sure, in this example,  `gaspi_segment_list` is called with a `num` which is the output of `gaspi_segment_num`?.  Using an arbitrary `num`, `gaspi_segment_list` will run, however the output for the missing rank is wrong and, as you mention, it should stop with an error.

**Comment by krzikalla** [comment]
Yes. gaspi_segment_num will return 1 on rank 3 but gaspi_segment_list will fail.

**Comment by acastanedam** [comment]
I am a bit confused, in the example the missing rank in the group is 2 not 3, right?. Therefore the `gaspi_segment_list` should fail for the rank 2 (not 3).

**Comment by acastanedam** [comment]
Right. Note also when GPI-2 is clone it points to the branch `next`, which was and is free of this issue. This will be also the case for the upcoming release.
Thanks for your feedback
