### ISSUE TITLE
Why a group requires at least two member?

### ISSUE THREAD

**Issue by dhinf** [cc-hpc-itwm/GPI-2#56]
The GASPI specification doesn't mention a restriction to the number of group members. Why GPI2 requires at least two members to  create a group?

**Comment by acastanedam** [comment]
Hi. In principle such restriction can be removed. Just one question, in which cases in particular a single member group will be useful?

**Comment by dhinf** [comment]
In case of plain group splitting. So you might end in a subgroup with one member only, representing a NUMA domain or a computation node.

**Comment by acastanedam** [comment]
Hi, thanks for the clarification. This constraint has been removed in the actual `next` branch.
