### ISSUE TITLE
Support for shared libraries

### ISSUE THREAD

**Issue by severinstrobl** [cc-hpc-itwm/GPI-2#57]
The support for building shared libraries is explicitly disabled in the configure script, with a message that doing so is not supported at the moment. Are there any known issues with using the shared libraries or is this a historic artifact?

https://github.com/cc-hpc-itwm/GPI-2/blob/c52bf44e846c1d31511eb22d2359b57693db6fad/configure.ac.in#L63-L66

**Comment by acastanedam** [comment]
Hi, the support for building shared libraries has been included in the `next` branch.
Best.
