### ISSUE TITLE
v1.4.0 Slurm Support | Intended usage

### ISSUE THREAD

**Issue by mflehmig** [cc-hpc-itwm/GPI-2#58]
Dear GPI2 community,

is there any documentation on the (intended) usage of GPI2 and Slurm? As I can see, gaspi_run executes "srun ..." but the machinefile needs to be provided by the user. This can be automated, right?

Best regards!

**Comment by rumach** [comment]
Hi there,

thanks for reporting this.

In docs/batch_examples/submit_to_slurm.sh there is an example on the usage of Slurm. 

With v1.5.0 should also be possible to call gaspi_run without providing a machinefile.

I hope this helps. Closing for now.
